site_name: kintone UI Component
repo_url: https://github.com/kintone/kintone-ui-component
site_url: https://kintone.github.io/kintone-ui-component

theme:
  name: 'material'
  custom_dir: 'custom_theme'
  favicon: favicon.ico
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
  logo:
    icon: 'cloud'

markdown_extensions:
  - admonition
extra_javascript:
  - 'js/extra.js'
extra_css:
  - 'style/extra.css'
extra:
    version: '0.1.4'
